version: '3.8'

services:
  web:
    build: .
    expose:
      - "5000"  # Exposes port 5000 to other services (but not to the host directly)
    volumes:
      - ./logs:/app/logs
    restart: always
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Maps port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always



